apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
  namespace: exam-board
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
        - name: student-service
          image: shahiddevops1/exam-result-system-student_service
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: POSTGRES_HOST
              value: postgres

            - name: POSTGRES_PORT
              value: "5432"

            - name: DJANGO_SECRET_KEY
              value: "change-this-secret-key"

            - name: DEBUG
              value: "True"

            - name: ADMIN_PORTAL_URL
              value: "http://admin-service:8001"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"