apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: exam-board
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  type: ClusterIP

  selector:
    app: student-service

  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP